### ISSUE TITLE
Fix issues found during September 2022 CDM conversion run

### ISSUE THREAD

**Issue by rjhd2** [glamod/glamod-nuim#62]
Some bugs found during that run - investigate and fix

**Comment by sjnoone** [comment]
**extract_station_config_info.py**
 The issue occurs when it finds no data just a header in a file .
Traceback (most recent call last):
  File "extract_station_config_info.py", line 179, in <module>
    main(station=args.station,
  File "extract_station_config_info.py", line 117, in main
    primary_id = df['primary_station_id'].iloc[0]
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
[sjnoone@sci3.jasmin.ac.uk code]$

**Comment by sjnoone** [comment]
**"hourly_qff_to_cdm_obs_v1.py"**
Not sure what causes this error needs investigating.

Traceback (most recent call last):
  File "hourly_qff_to_cdm_obs_v1.py", line 574, in <module>
    main(station=args.station, subset=args.subset, run_all=args.run_all, clobber=args.clobber)
  File "hourly_qff_to_cdm_obs_v1.py", line 381, in main
    dfslp['observation_value'] = dfslp['observation_value'].map(float)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/series.py", line 4161, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/base.py", line 870, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
ValueError: could not convert string to float: 'Null

**Comment by sjnoone** [comment]
**hourly_qff_to_cdm_obs_v1.py**
This occurs in all .py conversion codes  when it encounters a file with only header information. The df.iloc[1] needs top be changed to df.iloc[0] or we need to pick up when data empty files are written out earlier as errors.

Traceback (most recent call last):
  File "hourly_qff_to_cdm_obs_v1.py", line 574, in <module>
    main(station=args.station, subset=args.subset, run_all=args.run_all, clobber=args.clobber)
  File "hourly_qff_to_cdm_obs_v1.py", line 180, in main
    station_id = df.iloc[1]["Station_ID"] # NOTE: this is renamed below to "primary_station_id"
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by sjnoone** [comment]
**daily_to_cdm_header_v1.py** 
I think that the file extension is set wrong it should be .psv because the code reads in the obs_table.psv files. But just double check!
# Set the file extension for the subdaily obs psv files
IN_EXTENSION = ".qff"
OUT_EXTENSION = ".psv"
COMPRESSION = ""

**Comment by sjnoone** [comment]
Some of the conversions files were failing because of incorrect matching mingled station_id's. Could be a merge issue but might be the .qff code issue. Example .qff


Station_ID|Station_name|Year|Month|Day|Hour|Minute|Latitude|Longitude|Elevation|temperature|temperature_Source_Code|temperature_QC_flag|temperature_Source_Station_ID|dew_point_temperature|dew_point_temperature_Source_Code|dew_point_temperature_QC_flag|dew_point_temperature_Source_Station_ID|station_level_pressure|station_level_pressure_Source_Code|station_level_pressure_QC_flag|station_level_pressure_Source_Station_ID|sea_level_pressure|sea_level_pressure_Source_Code|sea_level_pressure_QC_flag|sea_level_pressure_Source_Station_ID|wind_direction|wind_direction_Source_Code|wind_direction_QC_flag|wind_direction_Source_Station_ID|wind_speed|wind_speed_Source_Code|wind_speed_QC_flag|wind_speed_Source_Station_ID
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|06|30|23|00|-16.9267|146.0033|124.0|22.4|319||031084|19.0|319||031084|||||||||135.0|319||031084|4.115552|319||031084
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|07|01|05|00|-16.9267|146.0033|124.0|25.0|319||031084|19.0|319||031084|||||||||90.0|319||031084|5.14444|319||031084
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|07|01|23|00|-16.9267|146.0033|124.0|23.3|319||031084|17.0|319||031084|||||||||90.0|319||031084|4.115552|319||031084
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|07|02|05|00|-16.9267|146.0033|124.0|24.4|319||031084|16.0|319||031084|||||||||90.0|319||031084|4.115552|319||031084
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|07|02|23|00|-16.9267|146.0033|124.0|22.2|319||031084|19.0|319||031084|||||||||157.5|319||031084|6.173328|319||031084
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|07|03|05|00|-16.9267|146.0033|124.0|24.4|319||031084|19.0|319||031084|||||||||157.5|319||031084|6.173328|319||031084
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|07|03|23|00|-16.9267|146.0033|124.0|23.1|319||031084|19.0|319||031084|||||||||157.5|319||031084|5.14444|319||031084
ASN00031084|FITZROY ISLAND LIGHTHOUSE|1968|07|04|05|00|-16.9267|146.0033|124.0|

mingle list has mingled station id as:AUS031084 not 031084|
same for all the following stations.
cdm_lite_r202208_ASM00094181.psv  cdm_lite_r202208_ASM00094978.psv  cdm_lite_r202208_ASN00001005.psv plus more!

**Comment by sjnoone** [comment]
this is the code from the inter_checks.py station-id is not defined in the code: need to be "target_station_id"

station_list = utils.get_station_list(restart_id=restart_id, end_id=end_id)
    station_IDs = station_list.id

    # read in all the neighbours for these stations to hold ready
    all_neighbours = read_neighbours(restart_id=restart_id, end_id=end_id)

    # now spin through each ID in the curtailed list
    for st, target_station_id in enumerate(station_IDs):
        print("{} {} ({}/{})".format([http://dt.datetime.now](https://t.co/98B1rf6a8L)(), target_station_id, st+1, station_IDs.shape[0]))

        if not clobber:
            # wanting to skip if files exist
            if os.path.exists(os.path.join(setup.SUBDAILY_BAD_DIR, "{:11s}.qff".format(station_id))):
                print("{} exists and clobber kwarg not set, skipping to next station.".format(
                    os.path.join(setup.SUBDAILY_BAD_DIR, "{:11s}.qff".format(target_station_id))))
                continue
 elif os.path.exists(os.path.join(setup.SUBDAILY_OUT_DIR, "{:11s}.qff".format(station_id))):
                print("{} exists and clobber kwarg not set, skipping to next station.".format(
                    os.path.join(setup.SUBDAILY_OUT_DIR, "{:11s}.qff".format(target_station_id))))
                continue
            else:
                # files don't exists, pass
                pass
        else:
            print("Overwriting output for {}".format(target_station_id))

**Comment by sjnoone** [comment]
hourly_qff_to_cdm_obs_v1.py 
The code has not outputted the correct report_id column imformation for some of the obs_tables.Which has  aknock on effect for the header extrcation. It is missing the hour e.g FII0000EFPU-1-2005-08-07-06:00. Also issue with the date_time should be 2005-08-07 06:00:00+00 
see  cdm_obs_r202208_ESM00078652.psv

observation_id|report_id|data_policy_licence|date_time|date_time_meaning|observation_duration|longitude|latitude|crs|z_coordinate|z_coordinate_type|observation_height_above_station_surface|observed_variable|secondary_variable|observation_value|value_significance|secondary_value|units|code_table|conversion_flag|location_method|location_precision|z_coordinate_method|bbox_min_longitude|bbox_max_longitude|bbox_min_latitude|bbox_max_latitude|spatial_representativeness|quality_flag|numerical_precision|sensor_id|sensor_automation_status|exposure_of_sensor|original_precision|original_units|original_code_table|original_value|conversion_method|processing_code|processing_level|adjustment_id|traceability|advanced_qc|advanced_uncertainty|advanced_homogenisation|advanced_assimilation_feedback|source_id
ESM00078652-1-2013-09-36-12|ESM00078652-1-2013-09|1|2013-09-18+00|1|0|-89.65|13.883||||2|36||294.75|12||5||0|||||||||1|0.01||||0.1|60||21.6|1||0|||||||220
ESM00078652-1-2013-09-85-12|ESM00078652-1-2013-09|1|2013-09-18+00|1|0|-89.65|13.883||||2|85||294.95|12||5||0|||||||||1|0.01||||0.1|60||21.8|1||0|||||||220
ESM00078652-1-2013-09-57-12|ESM00078652-1-2013-09|1|2013-09-18+00|1|0|-89.65|13.883||||2|57||93760|12||32||0|||||||||1|10||||0.1|530||937.6|7||0|||||||220

**Comment by sjnoone** [comment]
Just got the follwing error running the hourly_qff_to_cdm_obs_v1.py 

Processing /gws/nopw/j04/c3s311a_lot2/data/level1/land/level1c_sub_daily_data/v202208/CIN00200006.qff
Traceback (most recent call last):
  File "hourly_qff_to_cdm_obs_v1.py", line 582, in <module>
    main(station=args.station, subset=args.subset, run_all=args.run_all, clobber=args.clobber)
  File "hourly_qff_to_cdm_obs_v1.py", line 385, in main
    dfslp['observation_value'] = dfslp['observation_value'].map(float)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/series.py", line 4161, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/python3.8/site-packages/pandas/core/base.py", line 870, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
ValueError: could not convert string to float: 'Null'
